name: Tag new versions

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Determine new tag name
        id: tag
        run: ./scripts/tag.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.PAT }}
          tag: ${{ steps.tag.outputs.name }}
          generateReleaseNotes: true
